import SessionProviderWrapper from "../[locale]/SessionProviderWrapper";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProviderWrapper>
        <body>{children}</body>
      </SessionProviderWrapper>
    </html>
  )
}
